### PR TITLE
add test_men_tops_product_sorting suite

### PR DESCRIPTION
**Pull request by alenabaska**

### CODE REVIEW

**Review by aqaestuser — APPROVED** [review]

**Comment by alenabaska** [comment]
[TC_008.006.001 | Tops Page > items amount on the Page and common items amount > Checking the quantity of items in the grid view](https://trello.com/c/MAxBbfPz/525-tc008006001-tops-page-items-amount-on-the-page-and-common-items-amount-checking-the-quantity-of-items-in-the-grid-view)

**Comment by alenabaska** [comment]
[TC_008.006.002 | Tops Page > items amount on the Page and common items amount > Checking the quantity of items in the list view](https://trello.com/c/RASkgG5w/526-tc008006002-tops-page-items-amount-on-the-page-and-common-items-amount-checking-the-quantity-of-items-in-the-list-view)

**Comment by alenabaska** [comment]
[TC_008.007.001 | Tops Page > sort Items by: Position, Product Name and Price > Checking sorting items by Product Name ASC(A-Z)](https://trello.com/c/t0PrR1kV/527-tc008007001-tops-page-sort-items-by-position-product-name-and-price-checking-sorting-items-by-product-name-asca-z)

**Comment by alenabaska** [comment]
[TC_008.007.002 | Tops Page > sort Items by: Position, Product Name and Price > Checking sorting items by Product Name DESC(Z-A)](https://trello.com/c/V704iYJd/528-tc008007002-tops-page-sort-items-by-position-product-name-and-price-checking-sorting-items-by-product-name-descz-a)

**Comment by alenabaska** [comment]
[TC_008.007.003 | Tops Page > sort Items by: Position, Product Name and Price > Checking sorting items by Price ASC(0-9)](https://trello.com/c/UafQWr4y/529-tc008007003-tops-page-sort-items-by-position-product-name-and-price-checking-sorting-items-by-price-asc0-9)

**Comment by alenabaska** [comment]
[TC_008.007.004 | Tops Page > sort Items by: Position, Product Name and Price > Checking sorting items by Price DESC(9-0)](https://trello.com/c/y85SF81V/530-tc008007004-tops-page-sort-items-by-position-product-name-and-price-checking-sorting-items-by-price-desc9-0)

**Pull request merged**
