### PR TITLE
TC_012.013.001-002 | Verify URL and Title upon redirection

### PR DESCRIPTION
**Pull request by DenisProkofyev**

### CODE REVIEW

**Comment by DenisProkofyev** [comment]
[TC_012.013.001 | Footer > "Advanced Search" link > Redirection > Verify the opened page URL upon clicking on the appropriate link](https://trello.com/c/Enyq7hTs/697-tc012013001-footer-advanced-search-link-redirection-verify-the-opened-page-url-upon-clicking-on-the-appropriate-link)

**Comment by DenisProkofyev** [comment]
[TC_012.013.002 | Footer > "Advanced Search" link > Redirection > Verify the opened page title upon clicking on the appropriate link](https://trello.com/c/zhPffHiB/698-tc012013002-footer-advanced-search-link-redirection-verify-the-opened-page-title-upon-clicking-on-the-appropriate-link)

**Review by gomboc665 — APPROVED** [review]
looks good to me, thank you

**Comment by DenisProkofyev** [comment]
> looks good to me, thank you

Thank you, Aleksei!

**Pull request merged**
