### PR TITLE
TC_012.007.004 | added: test_text_block_for_typos_titled_your_choices…

### PR DESCRIPTION
**Pull request by evg-qa**
…_regarding_use_of_the_information_we_collect

### CODE REVIEW

**Comment by evg-qa** [comment]
[TC_012.007.004 | Footer > "Privacy and Cookie Policy" > Content > Verify the text block and title for typos titled ‘Your Choices Regarding Use Of The Information We Collect’.](https://trello.com/c/tdD4Gz5k/379-tc012007004-footer-privacy-and-cookie-policy-content-verify-the-text-block-and-title-for-typos-titled-your-choices-regarding-use)

**Review by gomboc665 — COMMENTED** [review]
Hi, looks good, interesting to check for typo mistakes, but I guess we can't search the required title by title.  In my opinion, it is better to find the element and check that this element has text and this text is our Title.

**Comment by evg-qa** [comment]
I find the element (header) by locator, then its text using the => .title method. then I check that text for grammatical mistakes.

I don't see what this has to do with checking that it is the header we are looking for, if its locator says so.

**Review by gomboc665 — APPROVED** [review]
yes, sorry, rerun these steps and now for me it's clear. here is no need to verify the text value, only typo check. approved.

**Pull request merged**
