### PR TITLE
TC_012.001.001-002, TC_012.011.001-002

### PR DESCRIPTION
**Pull request by gomboc665**
https://trello.com/c/SgonG9Je/404-tc012001001-footer-write-for-us-link-verify-visibility-of-the-link-for-the-page-for-writing-an-article
https://trello.com/c/2pVgBszn/405-tc012001002-footer-write-for-us-link-verify-clickability-of-the-link-for-the-page-for-writing-an-article
https://trello.com/c/BT0NUsoV/453-tc012011001-footer-self-verify-copyright-statement-in-the-footer
https://trello.com/c/oRFeXw5I/457-tc012011002-footer-self-text-verification-of-copyright-information

### CODE REVIEW

**Review by evg-qa — APPROVED** [review]

**Comment by gomboc665** [comment]
[TC_009.002.002 | Gear page > categories > The counter for the category 'Fitness Equipment'](https://trello.com/c/ZcigfmS7/160-tc009002002-gear-page-categories-the-counter-for-the-category-fitness-equipment)

**Comment by gomboc665** [comment]
[TC_009.002.004 | Gear page > categories > Verify the counter on the Gear Page for the category 'Bags' with counter on the Category Page](https://trello.com/c/sqWEnKkE/174-tc009002004-gear-page-categories-verify-the-counter-on-the-gear-page-for-the-category-bags-with-counter-on-the-category-page)

**Comment by gomboc665** [comment]
[TC_012.001.001 | Footer > "Write for us" link > Verify visibility of the link for the page for writing an article](https://trello.com/c/SgonG9Je/404-tc012001001-footer-write-for-us-link-verify-visibility-of-the-link-for-the-page-for-writing-an-article)

**Comment by gomboc665** [comment]
[TC_012.001.002 | Footer > "Write for us" link > Verify clickability of the link for the page for writing an article](https://trello.com/c/2pVgBszn/405-tc012001002-footer-write-for-us-link-verify-clickability-of-the-link-for-the-page-for-writing-an-article)

**Comment by gomboc665** [comment]
[TC_012.011.001 | Footer > Self > Verify Copyright statement in the footer](https://trello.com/c/BT0NUsoV/453-tc012011001-footer-self-verify-copyright-statement-in-the-footer)

**Comment by gomboc665** [comment]
[TC_012.011.002 | Footer > Self > Text verification of Copyright information](https://trello.com/c/oRFeXw5I/457-tc012011002-footer-self-text-verification-of-copyright-information)

**Comment by NikolayTikhomirov** [comment]
[TC_002.001.003 | Product page > Title > Product name in the page title](https://trello.com/c/TuvVv4eh/499-tc002001003-product-page-title-product-name-in-the-page-title)

**Pull request merged**
