### PR TITLE
TC 006.001.002 - 006.001.007

### PR DESCRIPTION
**Pull request by aglebkina**
Updated links in Data folder
Created Test Suite for TC 006.001.002 - 006.001.007 'Click to categories in New in Women's section'

### CODE REVIEW

**Comment by aglebkina** [comment]
[TC_006.001.006 | What’s New page > NEW IN WOMEN’S > Click on the Pants in NEW IN WOMEN’S](https://trello.com/c/D1zI1TyG/212-tc006001006-whats-new-page-new-in-womens-click-on-the-pants-in-new-in-womens)

**Comment by aglebkina** [comment]
[TC_006.001.002 | What’s New page > NEW IN WOMEN’S > Click on the Hoodies & Sweatershirts in NEW IN WOMEN’S](https://trello.com/c/SWSye4Hx/206-tc006001002-whats-new-page-new-in-womens-click-on-the-hoodies-sweatershirts-in-new-in-womens)

**Comment by aglebkina** [comment]
[TC_006.001.003 | What’s New page > NEW IN WOMEN’S > Click on the Jackets in NEW IN WOMEN’S](https://trello.com/c/5AslD2nk/207-tc006001003-whats-new-page-new-in-womens-click-on-the-jackets-in-new-in-womens)

**Comment by aglebkina** [comment]
[TC_006.001.004 | What’s New page > NEW IN WOMEN’S > Click on the Tees in NEW IN WOMEN’S](https://trello.com/c/Sy8JJrw6/210-tc006001004-whats-new-page-new-in-womens-click-on-the-tees-in-new-in-womens)

**Comment by aglebkina** [comment]
[TC_006.001.005 | What’s New page > NEW IN WOMEN’S > Click on the Bras & Tanks in NEW IN WOMEN’S](https://trello.com/c/p9yUjrtV/211-tc006001005-whats-new-page-new-in-womens-click-on-the-bras-tanks-in-new-in-womens)

**Comment by aglebkina** [comment]
[TC_006.001.007 | What’s New page > NEW IN WOMEN’S > Click on the Shorts in NEW IN WOMEN’S](https://trello.com/c/MKwfo62T/213-tc006001007-whats-new-page-new-in-womens-click-on-the-shorts-in-new-in-womens)

**Review by Alekmatv — APPROVED** [review]
Approved

**Pull request merged**
