### PR TITLE
ADD TC 006.012.001

### PR DESCRIPTION
**Pull request by OlenaKS**
TC 006.012.002
    TC 006.012.003

### CODE REVIEW

**Comment by OlenaKS** [comment]
[TC_006.012.001 | Performance Sportswear New > Product Item > Wish List, Compare, Add to Cart> Visibility, clickability, redirection](https://trello.com/c/sMHDEPVM/602-tc006012001-performance-sportswear-new-product-item-wish-list-compare-add-to-cart-visibility-clickability-redirection)

**Comment by OlenaKS** [comment]
[TC_006.012.002 | Performance Sportswear New > Product Item > Wish List, Compare, Add to Cart> Visibility, clickability, redirection](https://trello.com/c/XNfcovYv/603-tc006012002-performance-sportswear-new-product-item-wish-list-compare-add-to-cart-visibility-clickability-redirection)

**Comment by OlenaKS** [comment]
[TC_006.012.003 | Performance Sportswear New > Product Item > Wish List, Compare, Add to Cart> Visibility, clickability, redirection](https://trello.com/c/DMNzYGhN/604-tc006012003-performance-sportswear-new-product-item-wish-list-compare-add-to-cart-visibility-clickability-redirection)

**Review by aqaestuser — APPROVED** [review]
nice

**Pull request merged**
