### PR TITLE
TC_012.010.005-006 | Verify footer blocks links texts

### PR DESCRIPTION
**Pull request by DenisProkofyev**

### CODE REVIEW

**Comment by DenisProkofyev** [comment]
[TC_012.010.005 | Footer > Self > Set of links > Verify the 1st block links texts](https://trello.com/c/gNWK1gSz/700-tc012010005-footer-self-set-of-links-verify-the-1st-block-links-texts)

**Comment by DenisProkofyev** [comment]
[TC_012.010.006 | Footer > Self > Set of links > Verify the 2nd block links texts](https://trello.com/c/0kydj5z8/701-tc012010006-footer-self-set-of-links-verify-the-2nd-block-links-texts)

**Review by Alekmatv — APPROVED** [review]
Approved, thank you

**Comment by DenisProkofyev** [comment]
> Approved, thank you

Thank you!

**Pull request merged**
