### PR TITLE
TC_008.004.002| move to the Product page by clicking on the Product image (acceptance criteria 3)  , TC_008.004.003| move to the Product page by clicking on the Product name (acceptance criteria 4)

### PR DESCRIPTION
**Pull request by Grabova1983**

### CODE REVIEW

**Comment by Grabova1983** [comment]
[TC_008.004.003| Mens > Tops page > Product item >move to the Product page by clicking on the Product name (acceptance criteria 4)](https://trello.com/c/apivsps1/420-tc008004003-mens-tops-page-product-item-move-to-the-product-page-by-clicking-on-the-product-name-acceptance-criteria-4)

**Comment by Grabova1983** [comment]
[TC_008.004.003| Mens > Tops page > Product item >move to the Product page by clicking on the Product name (acceptance criteria 4)](https://trello.com/c/apivsps1/420-tc008004003-mens-tops-page-product-item-move-to-the-product-page-by-clicking-on-the-product-name-acceptance-criteria-4)

**Comment by Grabova1983** [comment]
[TC_008.004.003| Mens > Tops page > Product item >move to the Product page by clicking on the Product name (acceptance criteria 4)](https://trello.com/c/apivsps1/420-tc008004003-mens-tops-page-product-item-move-to-the-product-page-by-clicking-on-the-product-name-acceptance-criteria-4)

**Comment by Grabova1983** [comment]
[TC_008.004.002| Mens > Tops page > Product item >move to the Product page by clicking on the Product image (acceptance criteria 3)](https://trello.com/c/2XBf5jJO/419-tc008004002-mens-tops-page-product-item-move-to-the-product-page-by-clicking-on-the-product-image-acceptance-criteria-3)

**Review by verafes — APPROVED** [review]
It's good practice to have one pull request (PR) for each test case (TC) is recommended.

**Pull request merged**
