### PR TITLE
Added test case numbers to the tests

### PR DESCRIPTION
**Pull request by marinapauli**

### CODE REVIEW

**Review by gomboc665 — APPROVED** [review]
Approved,thank you

**Comment by marinapauli** [comment]
@gomboc665 Thank you. Did you delete my branch?

**Comment by gomboc665** [comment]
Yes, sorry, Did you still need it?

**Comment by marinapauli** [comment]
@gomboc665  no, no worries. It was just so quick:) All good! Thank you

**Comment by verafes** [comment]
I would be great to attach the link to Trello card in comments to PR. Comment can be added with 'Edit' button next to the name of PR. Thank you

**Pull request merged**
