### PR TITLE
TC_006.010.004-006

### PR DESCRIPTION
**Pull request by gomboc665**
[TC005](https://trello.com/c/GWAeNSFD/650-tc006010005-new-luma-yoga-collection-price-levels-ability-to-filter-items-by-price-level-available-item-colors)
[TC004](https://trello.com/c/aDXA52Zq/649-tc006010004-new-luma-yoga-collection-price-levels-ability-to-filter-items-by-price-level-images-and-names-of-items)
[TC006](https://trello.com/c/V31jYzQq/651-tc006010006-new-luma-yoga-collection-price-levels-ability-to-filter-items-by-price-level-reviews-for-available-items)

### CODE REVIEW

**Comment by gomboc665** [comment]
[TC_006.010.006 | New Luma Yoga Collection > Price levels> Ability to Filter Items by Price Level. Reviews for Available Items](https://trello.com/c/V31jYzQq/651-tc006010006-new-luma-yoga-collection-price-levels-ability-to-filter-items-by-price-level-reviews-for-available-items)

**Comment by gomboc665** [comment]
[TC_006.010.004 | New Luma Yoga Collection > Price levels> Ability to Filter Items by Price Level. Images and Names of Items](https://trello.com/c/aDXA52Zq/649-tc006010004-new-luma-yoga-collection-price-levels-ability-to-filter-items-by-price-level-images-and-names-of-items)

**Comment by gomboc665** [comment]
[TC_006.010.005 | New Luma Yoga Collection > Price levels> Ability to Filter Items by Price Level. Available Item Colors](https://trello.com/c/GWAeNSFD/650-tc006010005-new-luma-yoga-collection-price-levels-ability-to-filter-items-by-price-level-available-item-colors)

**Review by Alekmatv — APPROVED** [review]
Approved, thank you

**Pull request merged**
