### PR TITLE
TC_008.004.002| TC_008.004.003| TC_008.004.004|  (US_008.004 acceptance criteria 3,4,5)

### PR DESCRIPTION
**Pull request by Grabova1983**
TC_008.004.004| Mens > Tops page > Product item >move to the Product page by clicking on the BTN “Add to Cart“ (acceptance criteria 5)
TC_008.004.002| Mens > Tops page > Product item >move to the Product page by clicking on the Product image (acceptance criteria 3)
TC_008.004.003| Mens > Tops page > Product item >move to the Product page by clicking on the Product name (acceptance criteria 4)

### CODE REVIEW

**Comment by Grabova1983** [comment]
[TC_008.004.003| Mens > Tops page > Product item >move to the Product page by clicking on the Product name (acceptance criteria 4)](https://trello.com/c/apivsps1/420-tc008004003-mens-tops-page-product-item-move-to-the-product-page-by-clicking-on-the-product-name-acceptance-criteria-4)

**Comment by Grabova1983** [comment]
[TC_008.004.002| Mens > Tops page > Product item >move to the Product page by clicking on the Product image (acceptance criteria 3)](https://trello.com/c/2XBf5jJO/419-tc008004002-mens-tops-page-product-item-move-to-the-product-page-by-clicking-on-the-product-image-acceptance-criteria-3)

**Comment by Grabova1983** [comment]
[TC_008.004.004| Mens > Tops page > Product item >move to the Product page by clicking on the BTN “Add to Cart“ (acceptance criteria 5)](https://trello.com/c/m6bidvcc/421-tc008004004-mens-tops-page-product-item-move-to-the-product-page-by-clicking-on-the-btn-add-to-cart-acceptance-criteria-5)

**Comment by Grabova1983** [comment]
> @Grabova1983 Разрешите конфликты

Разрешила

**Review by KatyaMy — APPROVED** [review]

**Pull request merged**
