### PR TITLE
TC_006.001.001 

### PR DESCRIPTION
**Pull request by aglebkina**
[TC_006.001.001](https://trello.com/c/2L1jfzGK/203-tc006001001-whats-new-page-new-in-womens-user-is-able-to-see-section-new-in-womens) | What’s New page > NEW IN WOMEN’S > User is able to see section NEW IN WOMEN’S

### CODE REVIEW

**Comment by aglebkina** [comment]
[TC_006.001.001 | What’s New page > NEW IN WOMEN’S > User is able to see section NEW IN WOMEN’S](https://trello.com/c/2L1jfzGK/203-tc006001001-whats-new-page-new-in-womens-user-is-able-to-see-section-new-in-womens)

**Review by gomboc665 — COMMENTED** [review]
Hi, You need to use method text  in the error's text but you use WebElement instead

**Review by gomboc665 — APPROVED** [review]
approved, Thank you

**Comment by aglebkina** [comment]
> Hi, You need to use method text in the error's text but you use WebElement instead

@gomboc665 Thanks a lot for your review! Yes, I saw and I changed it inside element, so now in error it shoud be variable with text method.

**Pull request merged**
