### PR TITLE
Test privacy and cookie policy page evg

### PR DESCRIPTION
**Pull request by evg-qa**
This test should fail because the page that opens is 404, but the test passed. Please check

### CODE REVIEW

**Comment by evg-qa** [comment]
[TC_012.015.002 | Footer > "Privacy and Cookie Policy" > Navigation within text > Verify opening the contact page](https://trello.com/c/nNjRKkSE/384-tc012015002-footer-privacy-and-cookie-policy-navigation-within-text-verify-opening-the-contact-page)

**Comment by Alekmatv** [comment]
Hello! The test is passed because the condition in assert is true. The test only checks the current url, but not the page content
code

**Comment by evg-qa** [comment]
review please, thank you

**Review by Alekmatv — APPROVED** [review]
Approved

**Pull request merged**
