### PR TITLE
ADD TC 004.007.009

### PR DESCRIPTION
**Pull request by OlenaKS**
TC 004.007.010
    TC 004.007.011

### CODE REVIEW

**Comment by OlenaKS** [comment]
[TC_004.007.011 | Authorization > Recovering password](https://trello.com/c/Iq7Pm8wH/590-tc004007011-authorization-recovering-password)

**Comment by OlenaKS** [comment]
[TC_004.007.009 | Authorization > Recovering password](https://trello.com/c/Xj1bi2xo/588-tc004007009-authorization-recovering-password)

**Comment by OlenaKS** [comment]
[TC_004.007.010 | Authorization > Recovering password](https://trello.com/c/KKZz4unY/589-tc004007010-authorization-recovering-password)

**Comment by OlenaKS** [comment]
[TC_004.007.010 | Authorization > Recovering password](https://trello.com/c/KKZz4unY/589-tc004007010-authorization-recovering-password)

**Review by aqaestuser — APPROVED** [review]

**Pull request merged**
